// Generated by CoffeeScript 1.6.3
/*
	CACommandCenter
	Signature: Function[Class] ->
		add: (name[String], func[Function])
		exec: name[String]
	Description: A simple object class that stores and can
	be called to execute functions. Good for user-input commands
	as if has a fail-safe for non-existent functions.
	Dependencies: None
	Exports: CACommandCenter
*/


(function() {
  var Commander, exports;

  Commander = (function() {
    function Commander(commands) {
      this.commands = commands;
    }

    Commander.prototype.add = function(name, func) {
      return this.commands[name] = func;
    };

    Commander.prototype.exec = function(name) {
      var func;
      func = this.commands[name];
      if (func) {
        func();
      }
      return !!func;
    };

    Commander.prototype.test = function(name) {
      return !!this.commands[name];
    };

    return Commander;

  })();

  if (typeof exports !== 'undefined') {
    exports = Commander;
  } else {
    this.CACommandCenter = Commander;
  }

}).call(this);
