// Generated by CoffeeScript 1.6.3
/*
	CAForcePartial
	Signature: Function(, Scope[Object]) ->
	Description: Transforms any function in a 
	function that can have partial applied 
	arguments similar to Haskell functions.
	Dependencies: None
	Exports: CAForcePartial[Function]
*/


(function() {
  var CAForcePartial, exports;

  CAForcePartial = function(func, scope) {
    var args, lenf, next;
    if (scope == null) {
      scope = null;
    }
    args = [];
    lenf = func.length;
    next = function() {
      if (arguments.length === 0) {
        return func.apply(scope, args);
      } else {
        args = args.concat(arguments);
        if (args.length === lenf) {
          return func.apply(scope, args);
        } else {
          return next;
        }
      }
    };
    return next;
  };

  if (typeof exports !== 'undefined') {
    exports = CAForcePartial;
  } else {
    this.CASuperPartial = CAForcePartial;
  }

}).call(this);
