// Generated by CoffeeScript 1.6.3
/*
	CASocketRouter
	Signature: IO[instanceof Socket.IO]
	Description: An extension for Socket.IO that mimics the
	`app.router` middleware of Express/Connect to allow more
	modularity of Socket.IO.
	Dependencies: Socket.IO [Node.js]
	Exports: CASocketRouter[Function]
*/


(function() {
  var CASocketRouter;

  module.exports = function(io) {
    if (io) {
      return CASocketRouter(io);
    } else {
      return CASocketRouter;
    }
  };

  CASocketRouter = function(io) {
    io.routes = [];
    io.mount = function(event, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return io.routes[event] = callback;
    };
    return io.router = function(debug) {
      if (debug == null) {
        debug = false;
      }
      return io.sockets.on('connection', function(socket) {
        var callback, event, name, _i, _len, _ref, _results;
        _ref = io.routes;
        _results = [];
        for (callback = _i = 0, _len = _ref.length; _i < _len; callback = ++_i) {
          event = _ref[callback];
          name = 'io/' + event;
          _results.push(socket.on(event, function(data, done) {
            var next;
            if (debug) {
              console.time(name);
            }
            next = function(error, data) {
              if (debug) {
                console.timeEnd(name);
              }
              return done({
                error: error,
                data: data
              });
            };
            return callback.call(socket, data, next, io.sockets);
          }));
        }
        return _results;
      });
    };
  };

}).call(this);
