// Generated by CoffeeScript 1.6.3
/*
	CASuperPartial
	Signature: Object{partial[Function], _[Placeholder Object]}
	Description: Partial function application that can occur 
	anywhere within the function arguments, in any order.
	Dependencies: None
	Exports: CASuperPartial[Object]

	Example Usage:
		partialFunction = partial multiplyAllArguments
		(((partialFunction _, _, 800) 300, _, 1600) 500)()
		=> multiplyAllArguments(300, 500, 800, 1600)
		=> 192000000000
*/


(function() {
  var CASuperPartial, exports, partial, _,
    __slice = [].slice;

  _ = {
    'CASuperPartial': true
  };

  partial = function(func, scope) {
    var argument, params;
    if (scope == null) {
      scope = null;
    }
    params = [];
    argument = function() {
      var args, index, param, place, _i, _len, _results;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (args.length === 0) {
        return func.apply(scope, params);
      }
      _results = [];
      for (param = _i = 0, _len = args.length; _i < _len; param = ++_i) {
        index = args[param];
        if (param !== _) {
          place = function(index, value) {
            if (params[index]) {
              return place(index + 1, value);
            }
            return params[index] = value;
          };
          _results.push(place(index, param));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    return argument;
  };

  CASuperPartial = {
    partial: partial,
    _: _
  };

  if (typeof exports !== 'undefined') {
    exports = CASuperPartial;
  } else {
    this.CASuperPartial = CASuperPartial;
  }

}).call(this);
